import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import prisma from '../lib/prisma';


function Home({ feed, quizzes, categories }) {
    console.log(feed, ' in home')
    console.log(quizzes, 'quizzes')
    console.log(categories, 'categories')

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* <h1 className="text-3xl font-bold underline bg-red-100">
                Hello world! FROM TAILWIND!
            </h1> */}

            {/* {feed.map(item => {
                return (
                    <div key={item.id} className="bg-yellow-100 p-4">
                        <p>Created by: {item.author.name} - Contact {item.author.email}</p>


                        <p>{item.title}</p>
                        <p>{item.content}</p>
                    </div>
                )
            })} */}

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="">Quizio!</a>
                </h1>

                {/* <p className={styles.description}>
                    Get started by editing{' '}
                    <code className={styles.code}>pages/index.js</code>
                </p> */}



                {/* <div className={styles.grid}>
                    <a href="https://nextjs.org/docs" className={styles.card}>
                    <h2>Documentation &rarr;</h2>
                    <p>Find in-depth information about Next.js features and API.</p>
                    </a>
                    
                    <a href="https://nextjs.org/learn" className={styles.card}>
                    <h2>Learn &rarr;</h2>
                    <p>Learn about Next.js in an interactive course with quizzes!</p>
                    </a>
                    
                    <a
                    href="https://github.com/vercel/next.js/tree/canary/examples"
                    className={styles.card}
                    >
                    <h2>Examples &rarr;</h2>
                    <p>Discover and deploy boilerplate example Next.js projects.</p>
                    </a>
                    
                    <a
                    href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                    className={styles.card}
                    >
                    <h2>Deploy &rarr;</h2>
                    <p>
                    Instantly deploy your Next.js site to a public URL with Vercel.
                    </p>
                    </a>
                </div> */}
                <div className="flex mt-10 gap-4">
                    <div className="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow-md">
                        <a href="#">
                            <h5 className="mb-2 text-2xl font-bold text-black-900">Create a quiz</h5>
                        </a>
                        <p className="mb-3 font-normal text-gray-700 dark:text-black">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        <a href="/createQuiz" className="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-purple-500 rounded-lg hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-white-300 dark:bg-purple-600">
                            Create Now
                            <svg aria-hidden="true" className="w-4 h-4 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd"></path></svg>
                        </a>
                    </div>
                    <div className="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow-md">
                        <a href="#">
                            <h5 className="mb-2 text-2xl font-bold text-black-900">Take a quiz</h5>
                        </a>
                        <p className="mb-3 font-normal text-gray-700 dark:text-black">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        <a href="/categories" className="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-purple-500 rounded-lg hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-white-300 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-800">
                            Categories
                            <svg aria-hidden="true" className="w-4 h-4 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd"></path></svg>
                        </a>
                    </div>
                </div>
            </main>
            {/* <div className="bg-myColor p-3 ">HELLO</div> */}
            {/* <div className="flex flex-wrap">

                {categories.map(item => {
                    return (
                        <div key={item.category_id} className="bg-red-100 p-4 w-1/4">
                            {item.name}
                        </div>
                    )
                })}

            </div> */}

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' Deez '}
                    <span className={styles.logo}>
                        {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
                    </span>
                </a>
            </footer>
        </div>
    )
}

export const getServerSideProps = async () => {
    const feed = await prisma.post.findMany({
        where: { published: true },
        include: {
            author: {
                select: { name: true, email: true },
            },
        },
    });

    // include: { tags: { include: { tag: true } } },

    const quizzes = await prisma.quizzes.findMany({
        include: {
            questions: {},
            categories: { include: { category: true } }
        }
    })

    const categories = await prisma.categories.findMany()


    return {
        props: { feed, categories: JSON.parse(JSON.stringify(categories)), quizzes: JSON.parse(JSON.stringify(quizzes)) },
        // revalidate: 10,
    };
};

export default Home;